sude: false

language: node_js

node_js:
  - "stable"

before_script: 
  - psql -c 'create database allergease_test;' -U postgres

script:
  - npm run reboot
  - npm run coverage

services:
  -postgresql 

env:
  - NODE_ENV="testing"

deploy:
  provider: heroku
  api_key: 
    secure: 'bee269fd-8220-43f2-8009-236e598c81ff'
  app:
    master: allergease