sude: false

language: node_js

node_js:
  - "node"

before_script: 
  - psql -c 'create database allergease_test;' -U postgres

install: npm install 

cache: npm

script:
  - npm run reboot
  - npm run coverage

services:
  - postgresql 

env:
  - NODE_ENV="testing"