const table = "aliases";

exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex(table)
    .del()
    .then(function() {
      // Inserts seed entries
      return knex(table).insert([
        { id: 1, allergen_id: 1, description: "corn" },
        { id: 2, allergen_id: 1, description: "corn sugar" },
        { id: 3, allergen_id: 1, description: "corn syrup" },
        { id: 4, allergen_id: 1, description: "corn syrup solids" },
        { id: 5, allergen_id: 1, description: "cornstarch" },
        { id: 6, allergen_id: 1, description: "crystalline fructose" },
        { id: 7, allergen_id: 1, description: "crystalline glucose" },
        { id: 8, allergen_id: 1, description: "dextrose" },
        { id: 9, allergen_id: 1, description: "glucose" },
        { id: 10, allergen_id: 1, description: "glucose syrup" },
        { id: 11, allergen_id: 1, description: "hfcs" },
        { id: 12, allergen_id: 1, description: "high fructose corn syrup" },
        { id: 13, allergen_id: 1, description: "lecithin" },
        { id: 14, allergen_id: 1, description: "maltodextrin" },
        { id: 15, allergen_id: 2, description: "albumin" },
        { id: 16, allergen_id: 2, description: "apovitellin" },
        {
          id: 17,
          allergen_id: 2,
          description: "cholesterol free egg substitute"
        },
        { id: 18, allergen_id: 2, description: "conalbumin" },
        { id: 19, allergen_id: 2, description: "dried egg" },
        { id: 20, allergen_id: 2, description: "dried egg solids" },
        { id: 21, allergen_id: 2, description: "egg" },
        { id: 22, allergen_id: 2, description: "egg substitutes" },
        { id: 23, allergen_id: 2, description: "egg wash" },
        { id: 24, allergen_id: 2, description: "egg white" },
        { id: 25, allergen_id: 2, description: "egg yolk" },
        { id: 26, allergen_id: 2, description: "eggbeaters" },
        { id: 27, allergen_id: 2, description: "eggnog" },
        { id: 28, allergen_id: 2, description: "fat substitutes" },
        { id: 29, allergen_id: 2, description: "globulin" },
        { id: 30, allergen_id: 2, description: "globulin" },
        { id: 31, allergen_id: 2, description: "lecithin" },
        { id: 32, allergen_id: 2, description: "livetin" },
        { id: 33, allergen_id: 2, description: "livetin" },
        { id: 34, allergen_id: 2, description: "lysozyme" },
        { id: 35, allergen_id: 2, description: "mayonnaise" },
        { id: 36, allergen_id: 2, description: "meringue" },
        { id: 37, allergen_id: 2, description: "meringue powder" },
        { id: 38, allergen_id: 2, description: "ovalbumin" },
        { id: 39, allergen_id: 2, description: "ovoglobulin" },
        { id: 40, allergen_id: 2, description: "ovomacroglobulin" },
        { id: 41, allergen_id: 2, description: "ovomucin" },
        { id: 42, allergen_id: 2, description: "ovomucoid" },
        { id: 43, allergen_id: 2, description: "ovotransferrin" },
        { id: 44, allergen_id: 2, description: "ovovitelia" },
        { id: 45, allergen_id: 2, description: "ovovitellin" },
        { id: 46, allergen_id: 2, description: "powdered eggs" },
        { id: 47, allergen_id: 2, description: "silici albuminate" },
        { id: 48, allergen_id: 2, description: "silico-albuminate" },
        { id: 49, allergen_id: 2, description: "simplesse" },
        { id: 50, allergen_id: 2, description: "surimi" },
        { id: 51, allergen_id: 2, description: "trailblazer" },
        { id: 52, allergen_id: 2, description: "vitellin" },
        { id: 53, allergen_id: 2, description: "whole egg" },
        { id: 54, allergen_id: 3, description: "albacore" },
        { id: 55, allergen_id: 3, description: "anchovy" },
        { id: 56, allergen_id: 3, description: "bass" },
        { id: 57, allergen_id: 3, description: "bluefish" },
        { id: 58, allergen_id: 3, description: "bonito" },
        { id: 59, allergen_id: 3, description: "calamari" },
        { id: 60, allergen_id: 3, description: "carp" },
        { id: 61, allergen_id: 3, description: "catfish" },
        { id: 62, allergen_id: 3, description: "char" },
        { id: 63, allergen_id: 3, description: "clam" },
        { id: 64, allergen_id: 3, description: "cockle" },
        { id: 65, allergen_id: 3, description: "cod" },
        { id: 66, allergen_id: 3, description: "conch" },
        { id: 67, allergen_id: 3, description: "crab" },
        { id: 68, allergen_id: 3, description: "crayfish" },
        { id: 69, allergen_id: 3, description: "crustaceans" },
        { id: 70, allergen_id: 3, description: "eel" },
        { id: 71, allergen_id: 3, description: "escargot" },
        { id: 72, allergen_id: 3, description: "fish" },
        { id: 73, allergen_id: 3, description: "halibut" },
        { id: 74, allergen_id: 3, description: "herring" },
        { id: 75, allergen_id: 3, description: "lobster" },
        { id: 76, allergen_id: 3, description: "mackerel" },
        { id: 77, allergen_id: 3, description: "mahi-mahi" },
        { id: 78, allergen_id: 3, description: "marlin" },
        { id: 79, allergen_id: 3, description: "mussels" },
        { id: 80, allergen_id: 3, description: "octopus" },
        { id: 81, allergen_id: 3, description: "orange roughy" },
        { id: 82, allergen_id: 3, description: "pickerel" },
        { id: 83, allergen_id: 3, description: "pike" },
        { id: 84, allergen_id: 3, description: "pollock" },
        { id: 85, allergen_id: 3, description: "prawns" },
        { id: 86, allergen_id: 3, description: "rockfish" },
        { id: 87, allergen_id: 3, description: "salmon" },
        { id: 88, allergen_id: 3, description: "sardine" },
        { id: 89, allergen_id: 3, description: "scallops" },
        { id: 90, allergen_id: 3, description: "sea urchin" },
        { id: 91, allergen_id: 3, description: "shark" },
        { id: 92, allergen_id: 3, description: "shellfish" },
        { id: 93, allergen_id: 3, description: "shrimp" },
        { id: 94, allergen_id: 3, description: "smelt" },
        { id: 95, allergen_id: 3, description: "snails" },
        { id: 96, allergen_id: 3, description: "snapper" },
        { id: 97, allergen_id: 3, description: "squid" },
        { id: 98, allergen_id: 3, description: "swordfish" },
        { id: 99, allergen_id: 3, description: "tilapia" },
        { id: 100, allergen_id: 3, description: "trout" },
        { id: 101, allergen_id: 3, description: "tuna" },
        { id: 102, allergen_id: 3, description: "walleye" },
        { id: 103, allergen_id: 3, description: "white fish" },
        { id: 104, allergen_id: 3, description: "yellow fin" },
        { id: 105, allergen_id: 4, description: "1% milk" },
        { id: 106, allergen_id: 4, description: "2% milk" },
        { id: 107, allergen_id: 4, description: "acid whey" },
        { id: 108, allergen_id: 4, description: "acidophilus milk" },
        { id: 109, allergen_id: 4, description: "ammonium caseinate" },
        { id: 110, allergen_id: 4, description: "anhydrous milk fat" },
        { id: 111, allergen_id: 4, description: "artificial butter" },
        { id: 112, allergen_id: 4, description: "artificial butter flavor" },
        { id: 113, allergen_id: 4, description: "artificial cheese flavor" },
        { id: 114, allergen_id: 4, description: "butter" },
        { id: 115, allergen_id: 4, description: "butter extract" },
        { id: 116, allergen_id: 4, description: "butter fat" },
        { id: 117, allergen_id: 4, description: "butter flavored oil" },
        { id: 118, allergen_id: 4, description: "butter solids" },
        { id: 119, allergen_id: 4, description: "buttermilk" },
        { id: 120, allergen_id: 4, description: "buttermilk blend" },
        { id: 121, allergen_id: 4, description: "buttermilk solids" },
        { id: 122, allergen_id: 4, description: "calcium caseinate" },
        { id: 123, allergen_id: 4, description: "casein" },
        { id: 124, allergen_id: 4, description: "casein hydrolysate" },
        { id: 125, allergen_id: 4, description: "caseinate" },
        { id: 126, allergen_id: 4, description: "cheese" },
        { id: 127, allergen_id: 4, description: "cheese flavor" },
        { id: 128, allergen_id: 4, description: "cheese food" },
        { id: 129, allergen_id: 4, description: "condensed milk" },
        { id: 130, allergen_id: 4, description: "cottage cheese" },
        { id: 131, allergen_id: 4, description: "cream" },
        { id: 132, allergen_id: 4, description: "cream cheese" },
        { id: 133, allergen_id: 4, description: "cultured milk" },
        { id: 134, allergen_id: 4, description: "curds" },
        { id: 135, allergen_id: 4, description: "curds" },
        { id: 136, allergen_id: 4, description: "cured whey" },
        { id: 137, allergen_id: 4, description: "custard" },
        { id: 138, allergen_id: 4, description: "dairy butter" },
        { id: 139, allergen_id: 4, description: "dairy product solids" },
        { id: 140, allergen_id: 4, description: "delactosed whey" },
        { id: 141, allergen_id: 4, description: "demineralized whey" },
        { id: 142, allergen_id: 4, description: "dms" },
        { id: 143, allergen_id: 4, description: "dried milk" },
        { id: 144, allergen_id: 4, description: "dry milk" },
        { id: 145, allergen_id: 4, description: "dry milk solids" },
        { id: 146, allergen_id: 4, description: "evaporated milk" },
        { id: 147, allergen_id: 4, description: "fat‐free milk" },
        { id: 148, allergen_id: 4, description: "frozen yogurt" },
        { id: 149, allergen_id: 4, description: "fully cream milk powder" },
        { id: 150, allergen_id: 4, description: "galactose" },
        { id: 151, allergen_id: 4, description: "ghee" },
        { id: 152, allergen_id: 4, description: "goat’s milk" },
        { id: 153, allergen_id: 4, description: "half & half" },
        { id: 154, allergen_id: 4, description: "hydrolysate" },
        { id: 155, allergen_id: 4, description: "hydrolyzed casein" },
        { id: 156, allergen_id: 4, description: "hydrolyzed milk protein" },
        { id: 157, allergen_id: 4, description: "hydrolyzed whey" },
        { id: 158, allergen_id: 4, description: "ice cream" },
        { id: 159, allergen_id: 4, description: "ice milk" },
        { id: 160, allergen_id: 4, description: "imitation cheese" },
        { id: 161, allergen_id: 4, description: "imitation sour cream" },
        {
          id: 162,
          allergen_id: 4,
          description: "iron caseinate magnesium caseinate"
        },
        { id: 163, allergen_id: 4, description: "lactaid milk" },
        { id: 164, allergen_id: 4, description: "lactalbumin" },
        { id: 165, allergen_id: 4, description: "lactalbumin phosphate" },
        { id: 166, allergen_id: 4, description: "lactate" },
        { id: 167, allergen_id: 4, description: "lactate solids" },
        { id: 168, allergen_id: 4, description: "lactitol monohydrate" },
        { id: 169, allergen_id: 4, description: "lactoferrin" },
        { id: 170, allergen_id: 4, description: "lactoglobulin" },
        { id: 171, allergen_id: 4, description: "lactose" },
        { id: 172, allergen_id: 4, description: "lactose free milk" },
        { id: 173, allergen_id: 4, description: "lactulose" },
        { id: 174, allergen_id: 4, description: "lactyc yeast" },
        { id: 175, allergen_id: 4, description: "low fat milk" },
        { id: 176, allergen_id: 4, description: "magnesium caseinate" },
        { id: 177, allergen_id: 4, description: "malted milk" },
        { id: 178, allergen_id: 4, description: "milk derivative" },
        { id: 179, allergen_id: 4, description: "milk fat" },
        { id: 180, allergen_id: 4, description: "milk powder" },
        { id: 181, allergen_id: 4, description: "milk protein" },
        { id: 182, allergen_id: 4, description: "milk protein hydrolysate" },
        { id: 183, allergen_id: 4, description: "milk solid pastes" },
        { id: 184, allergen_id: 4, description: "milk solids" },
        { id: 185, allergen_id: 4, description: "modified milk ingredients" },
        { id: 186, allergen_id: 4, description: "natural butter" },
        { id: 187, allergen_id: 4, description: "natural butter flavor" },
        { id: 188, allergen_id: 4, description: "natural cheese flavor" },
        { id: 189, allergen_id: 4, description: "nisin preparation" },
        { id: 190, allergen_id: 4, description: "nonfat dry milk" },
        { id: 191, allergen_id: 4, description: "nonfat milk" },
        { id: 192, allergen_id: 4, description: "nonfat milk solids" },
        { id: 193, allergen_id: 4, description: "nougat" },
        { id: 194, allergen_id: 4, description: "opta" },
        { id: 195, allergen_id: 4, description: "pasteurized milk" },
        { id: 196, allergen_id: 4, description: "potassium caseinate" },
        { id: 197, allergen_id: 4, description: "powdered milk" },
        { id: 198, allergen_id: 4, description: "powdered whey" },
        { id: 199, allergen_id: 4, description: "protein hydrolysate" },
        { id: 200, allergen_id: 4, description: "pudding" },
        { id: 201, allergen_id: 4, description: "quark" },
        { id: 202, allergen_id: 4, description: "recaldent" },
        { id: 203, allergen_id: 4, description: "reduced mineral whey" },
        { id: 204, allergen_id: 4, description: "regular yogurt" },
        { id: 205, allergen_id: 4, description: "rennet" },
        { id: 206, allergen_id: 4, description: "rennet casein" },
        { id: 207, allergen_id: 4, description: "sheep’s milk" },
        { id: 208, allergen_id: 4, description: "sherbet" },
        { id: 209, allergen_id: 4, description: "simplesse" },
        { id: 210, allergen_id: 4, description: "skim milk" },
        { id: 211, allergen_id: 4, description: "skim milk powder" },
        { id: 212, allergen_id: 4, description: "sodium caseinate" },
        { id: 213, allergen_id: 4, description: "sour cream" },
        { id: 214, allergen_id: 4, description: "sour cream solids" },
        { id: 215, allergen_id: 4, description: "sour milk" },
        { id: 216, allergen_id: 4, description: "sour milk solids" },
        {
          id: 217,
          allergen_id: 4,
          description: "sweet cream buttermilk powder"
        },
        { id: 218, allergen_id: 4, description: "sweet dairy whey" },
        { id: 219, allergen_id: 4, description: "sweetened condensed milk" },
        {
          id: 220,
          allergen_id: 4,
          description: "sweetened condensed skim milk"
        },
        {
          id: 221,
          allergen_id: 4,
          description: "vegetarian cheeses with casein"
        },
        { id: 222, allergen_id: 4, description: "whey" },
        { id: 223, allergen_id: 4, description: "whey hydrolysate" },
        { id: 224, allergen_id: 4, description: "whey powder" },
        { id: 225, allergen_id: 4, description: "whey protein" },
        { id: 226, allergen_id: 4, description: "whey protein concentrate" },
        { id: 227, allergen_id: 4, description: "whey protein hydrolysate" },
        { id: 228, allergen_id: 4, description: "whey solids" },
        { id: 229, allergen_id: 4, description: "whipped butter" },
        { id: 230, allergen_id: 4, description: "whipped cream" },
        { id: 231, allergen_id: 4, description: "whole milk" },
        { id: 232, allergen_id: 4, description: "yogurt" },
        { id: 233, allergen_id: 4, description: "yogurt powder" },
        { id: 234, allergen_id: 4, description: "zinc caseinate" },
        { id: 235, allergen_id: 5, description: "arachic oil" },
        { id: 236, allergen_id: 5, description: "arachide" },
        { id: 237, allergen_id: 5, description: "arachis" },
        { id: 238, allergen_id: 5, description: "arachis hypogaea" },
        { id: 239, allergen_id: 5, description: "arachis oil" },
        { id: 240, allergen_id: 5, description: "artificial nuts" },
        { id: 241, allergen_id: 5, description: "beer nuts" },
        { id: 242, allergen_id: 5, description: "boiled peanuts" },
        { id: 243, allergen_id: 5, description: "cacahouète" },
        { id: 244, allergen_id: 5, description: "cacahouette" },
        { id: 245, allergen_id: 5, description: "cacahuète" },
        { id: 246, allergen_id: 5, description: "cold pressed peanut oil" },
        { id: 247, allergen_id: 5, description: "crushed nuts" },
        { id: 248, allergen_id: 5, description: "crushed peanuts" },
        { id: 249, allergen_id: 5, description: "earth nuts" },
        { id: 250, allergen_id: 5, description: "expelled peanut oil" },
        { id: 251, allergen_id: 5, description: "extruded peanut oil" },
        { id: 252, allergen_id: 5, description: "goober nuts" },
        { id: 253, allergen_id: 5, description: "goober peas" },
        { id: 254, allergen_id: 5, description: "ground nuts" },
        { id: 255, allergen_id: 5, description: "ground peanuts" },
        { id: 256, allergen_id: 5, description: "hydrolyzed peanut protein" },
        { id: 257, allergen_id: 5, description: "mandelonas" },
        { id: 258, allergen_id: 5, description: "mixed nuts" },
        { id: 259, allergen_id: 5, description: "monkey nuts" },
        { id: 260, allergen_id: 5, description: "nu nuts flavored nuts" },
        { id: 261, allergen_id: 5, description: "nu-nuts" },
        { id: 262, allergen_id: 5, description: "nut meats" },
        { id: 263, allergen_id: 5, description: "nut pieces" },
        { id: 264, allergen_id: 5, description: "nutmeat" },
        { id: 265, allergen_id: 5, description: "peanut butter" },
        { id: 266, allergen_id: 5, description: "peanut butter chips" },
        { id: 267, allergen_id: 5, description: "peanut butter morsels" },
        { id: 268, allergen_id: 5, description: "peanut flour" },
        { id: 269, allergen_id: 5, description: "peanut oil" },
        { id: 270, allergen_id: 5, description: "peanut paste" },
        { id: 271, allergen_id: 5, description: "peanut sauce" },
        { id: 272, allergen_id: 5, description: "peanut syrup" },
        { id: 273, allergen_id: 5, description: "peanuts" },
        { id: 274, allergen_id: 5, description: "spanish peanuts" },
        { id: 275, allergen_id: 5, description: "valencias" },
        { id: 276, allergen_id: 5, description: "virginia peanuts" },
        { id: 277, allergen_id: 6, description: "benne" },
        { id: 278, allergen_id: 6, description: "benne seed" },
        { id: 279, allergen_id: 6, description: "benniseed" },
        { id: 280, allergen_id: 6, description: "flavouring" },
        { id: 281, allergen_id: 6, description: "gingelly" },
        { id: 282, allergen_id: 6, description: "gingelly oil" },
        { id: 283, allergen_id: 6, description: "seeds" },
        { id: 284, allergen_id: 6, description: "sesame" },
        { id: 285, allergen_id: 6, description: "sesame seed" },
        { id: 286, allergen_id: 6, description: "sesamol" },
        { id: 287, allergen_id: 6, description: "sesamolina" },
        { id: 288, allergen_id: 6, description: "sesamum indicum" },
        { id: 289, allergen_id: 6, description: "sim sim" },
        { id: 290, allergen_id: 6, description: "tahina" },
        { id: 291, allergen_id: 6, description: "tahini" },
        { id: 292, allergen_id: 6, description: "til" },
        { id: 293, allergen_id: 6, description: "vegetable oil" },
        { id: 294, allergen_id: 7, description: "bean curd" },
        { id: 295, allergen_id: 7, description: "concentrate soy protein" },
        { id: 296, allergen_id: 7, description: "diglyceride" },
        { id: 297, allergen_id: 7, description: "edamame" },
        { id: 298, allergen_id: 7, description: "freeze dried tofu" },
        { id: 299, allergen_id: 7, description: "grilled tofu" },
        { id: 300, allergen_id: 7, description: "hydrolyzed soy protein" },
        { id: 301, allergen_id: 7, description: "isolate soy protein" },
        { id: 302, allergen_id: 7, description: "kinako" },
        { id: 303, allergen_id: 7, description: "kouridofu" },
        { id: 304, allergen_id: 7, description: "koya dofu" },
        { id: 305, allergen_id: 7, description: "lecithin" },
        { id: 306, allergen_id: 7, description: "miso" },
        { id: 307, allergen_id: 7, description: "monoglyceride" },
        { id: 308, allergen_id: 7, description: "natto" },
        { id: 309, allergen_id: 7, description: "okara" },
        { id: 310, allergen_id: 7, description: "roasted soybean flour" },
        { id: 311, allergen_id: 7, description: "shoyu" },
        { id: 312, allergen_id: 7, description: "soja" },
        { id: 313, allergen_id: 7, description: "soy albumin" },
        { id: 314, allergen_id: 7, description: "soy concentrate" },
        { id: 315, allergen_id: 7, description: "soy fiber" },
        { id: 316, allergen_id: 7, description: "soy formula" },
        { id: 317, allergen_id: 7, description: "soy grits" },
        { id: 318, allergen_id: 7, description: "soy lecithin" },
        { id: 319, allergen_id: 7, description: "soy milk" },
        { id: 320, allergen_id: 7, description: "soy miso" },
        { id: 321, allergen_id: 7, description: "soy nut butter" },
        { id: 322, allergen_id: 7, description: "soy nuts" },
        { id: 323, allergen_id: 7, description: "soy protein " },
        { id: 324, allergen_id: 7, description: "soy protein concentrate" },
        { id: 325, allergen_id: 7, description: "soy protein isolate" },
        { id: 326, allergen_id: 7, description: "soy pulp" },
        { id: 327, allergen_id: 7, description: "soy sauce" },
        { id: 328, allergen_id: 7, description: "soy sprouts" },
        { id: 329, allergen_id: 7, description: "soya" },
        { id: 330, allergen_id: 7, description: "soya flour" },
        { id: 331, allergen_id: 7, description: "soyabeans" },
        { id: 332, allergen_id: 7, description: "soybean" },
        { id: 333, allergen_id: 7, description: "soybean curd" },
        { id: 334, allergen_id: 7, description: "soybean curds" },
        { id: 335, allergen_id: 7, description: "soybean flour" },
        { id: 336, allergen_id: 7, description: "soybean granules" },
        { id: 337, allergen_id: 7, description: "soybean paste" },
        { id: 338, allergen_id: 7, description: "soybeans" },
        { id: 339, allergen_id: 7, description: "soybeans in pods" },
        { id: 340, allergen_id: 7, description: "supro" },
        { id: 341, allergen_id: 7, description: "tamari" },
        { id: 342, allergen_id: 7, description: "tempeh" },
        { id: 343, allergen_id: 7, description: "teriyaki sauce" },
        { id: 344, allergen_id: 7, description: "textured soy flour" },
        { id: 345, allergen_id: 7, description: "textured soy protein" },
        { id: 346, allergen_id: 7, description: "textured vegetable protein" },
        { id: 347, allergen_id: 7, description: "tofu" },
        { id: 348, allergen_id: 7, description: "tsf" },
        { id: 349, allergen_id: 7, description: "tsp" },
        { id: 350, allergen_id: 7, description: "tvp" },
        { id: 351, allergen_id: 7, description: "vegetable protein" },
        { id: 352, allergen_id: 7, description: "yaki-dofu" },
        { id: 353, allergen_id: 7, description: "yuba" },
        { id: 354, allergen_id: 8, description: "calcium bisulphite" },
        { id: 355, allergen_id: 8, description: "calcium sulphite" },
        { id: 356, allergen_id: 8, description: "e220" },
        { id: 357, allergen_id: 8, description: "e221" },
        { id: 358, allergen_id: 8, description: "e222" },
        { id: 359, allergen_id: 8, description: "e223" },
        { id: 360, allergen_id: 8, description: "e224" },
        { id: 361, allergen_id: 8, description: "e225" },
        { id: 362, allergen_id: 8, description: "e226" },
        { id: 363, allergen_id: 8, description: "e227" },
        { id: 364, allergen_id: 8, description: "e228" },
        { id: 365, allergen_id: 8, description: "potassium bisulphite" },
        { id: 366, allergen_id: 8, description: "potassium metabisulphite" },
        { id: 367, allergen_id: 8, description: "sodium bisulphite" },
        { id: 368, allergen_id: 8, description: "sodium metabisulphite" },
        { id: 369, allergen_id: 8, description: "sodium sulphite" },
        { id: 370, allergen_id: 8, description: "sulphite" },
        { id: 371, allergen_id: 8, description: "sulphiting agent" },
        { id: 372, allergen_id: 8, description: "sulphur dioxide" },
        { id: 373, allergen_id: 8, description: "sulphurous acid" },
        { id: 374, allergen_id: 9, description: "almond" },
        { id: 375, allergen_id: 9, description: "almond paste" },
        { id: 376, allergen_id: 9, description: "almonds" },
        { id: 377, allergen_id: 9, description: "anacardium nuts" },
        { id: 378, allergen_id: 9, description: "beechnut" },
        { id: 379, allergen_id: 9, description: "brazil nut" },
        { id: 380, allergen_id: 9, description: "bush nut" },
        { id: 381, allergen_id: 9, description: "butternut" },
        { id: 382, allergen_id: 9, description: "calisson" },
        { id: 383, allergen_id: 9, description: "cashew" },
        { id: 384, allergen_id: 9, description: "chestnut" },
        { id: 385, allergen_id: 9, description: "coconut" },
        { id: 386, allergen_id: 9, description: "filbert" },
        { id: 387, allergen_id: 9, description: "ginko nut" },
        { id: 388, allergen_id: 9, description: "hazelnut" },
        { id: 389, allergen_id: 9, description: "hazelnuts" },
        { id: 390, allergen_id: 9, description: "hickory nut" },
        { id: 391, allergen_id: 9, description: "lichee nut" },
        { id: 392, allergen_id: 9, description: "macadamia nut" },
        { id: 393, allergen_id: 9, description: "mandelonas" },
        { id: 394, allergen_id: 9, description: "marzipan" },
        { id: 395, allergen_id: 9, description: "nangai nut" },
        { id: 396, allergen_id: 9, description: "nu-nuts" },
        { id: 397, allergen_id: 9, description: "nut meats" },
        { id: 398, allergen_id: 9, description: "pecan" },
        { id: 399, allergen_id: 9, description: "pecans" },
        { id: 400, allergen_id: 9, description: "pignolias" },
        { id: 401, allergen_id: 9, description: "pine nut" },
        { id: 402, allergen_id: 9, description: "pistachio" },
        { id: 403, allergen_id: 9, description: "pistachio nuts" },
        { id: 404, allergen_id: 9, description: "queensland nut" },
        { id: 405, allergen_id: 9, description: "shea nut" },
        { id: 406, allergen_id: 9, description: "tree nuts" },
        { id: 407, allergen_id: 9, description: "walnut" },
        { id: 408, allergen_id: 10, description: "all purpose flour" },
        { id: 409, allergen_id: 10, description: "atta" },
        { id: 410, allergen_id: 10, description: "atta flour" },
        { id: 411, allergen_id: 10, description: "bread" },
        { id: 412, allergen_id: 10, description: "bread crumbs" },
        { id: 413, allergen_id: 10, description: "bread flour" },
        { id: 414, allergen_id: 10, description: "bromated flour" },
        { id: 415, allergen_id: 10, description: "bulgur" },
        { id: 416, allergen_id: 10, description: "cake flour" },
        { id: 417, allergen_id: 10, description: "cereal extract" },
        { id: 418, allergen_id: 10, description: "club flour" },
        { id: 419, allergen_id: 10, description: "common flour" },
        { id: 420, allergen_id: 10, description: "couscous" },
        { id: 421, allergen_id: 10, description: "cracker meal" },
        { id: 422, allergen_id: 10, description: "dinkel" },
        { id: 423, allergen_id: 10, description: "durum" },
        { id: 424, allergen_id: 10, description: "durum flour" },
        { id: 425, allergen_id: 10, description: "einkorn" },
        { id: 426, allergen_id: 10, description: "einkorn flour" },
        { id: 427, allergen_id: 10, description: "emmer " },
        { id: 428, allergen_id: 10, description: "emmer flour" },
        { id: 429, allergen_id: 10, description: "enriched flour" },
        { id: 430, allergen_id: 10, description: "farina" },
        { id: 431, allergen_id: 10, description: "farina flour" },
        { id: 432, allergen_id: 10, description: "farro" },
        { id: 433, allergen_id: 10, description: "fu" },
        { id: 434, allergen_id: 10, description: "fu gluten" },
        { id: 435, allergen_id: 10, description: "gluten" },
        { id: 436, allergen_id: 10, description: "graham flour" },
        { id: 437, allergen_id: 10, description: "ground flour" },
        { id: 438, allergen_id: 10, description: "high gluten flour" },
        { id: 439, allergen_id: 10, description: "high protein flour" },
        { id: 440, allergen_id: 10, description: "instant pastry flour" },
        { id: 441, allergen_id: 10, description: "kamut" },
        { id: 442, allergen_id: 10, description: "kamut flour" },
        { id: 443, allergen_id: 10, description: "khorasan wheat" },
        { id: 444, allergen_id: 10, description: "maida flour" },
        { id: 445, allergen_id: 10, description: "malt" },
        { id: 446, allergen_id: 10, description: "malt extract" },
        { id: 447, allergen_id: 10, description: "matza" },
        { id: 448, allergen_id: 10, description: "matza meal" },
        { id: 449, allergen_id: 10, description: "matzah" },
        { id: 450, allergen_id: 10, description: "matzah meal" },
        { id: 451, allergen_id: 10, description: "matzo" },
        { id: 452, allergen_id: 10, description: "matzo meal" },
        { id: 453, allergen_id: 10, description: "matzoh" },
        { id: 454, allergen_id: 10, description: "matzoh meal" },
        { id: 455, allergen_id: 10, description: "noodles, pasta" },
        { id: 456, allergen_id: 10, description: "pasta noodles" },
        { id: 457, allergen_id: 10, description: "phosphated flour" },
        { id: 458, allergen_id: 10, description: "plain flour" },
        { id: 459, allergen_id: 10, description: "protein flour" },
        { id: 460, allergen_id: 10, description: "seitan" },
        { id: 461, allergen_id: 10, description: "self-rising flour" },
        { id: 462, allergen_id: 10, description: "semolina" },
        { id: 463, allergen_id: 10, description: "semolina flour" },
        { id: 464, allergen_id: 10, description: "soft wheat flour" },
        { id: 465, allergen_id: 10, description: "spelt" },
        { id: 466, allergen_id: 10, description: "spelt flour" },
        { id: 467, allergen_id: 10, description: "sprouted wheat" },
        { id: 468, allergen_id: 10, description: "steel ground flour" },
        { id: 469, allergen_id: 10, description: "stone flour" },
        { id: 470, allergen_id: 10, description: "tabbouleh" },
        { id: 471, allergen_id: 10, description: "triticale" },
        { id: 472, allergen_id: 10, description: "triticale flour" },
        { id: 473, allergen_id: 10, description: "triticum" },
        { id: 474, allergen_id: 10, description: "triticum aestivum" },
        { id: 475, allergen_id: 10, description: "triticum flour" },
        { id: 476, allergen_id: 10, description: "unbleached flour" },
        { id: 477, allergen_id: 10, description: "vital gluten" },
        { id: 478, allergen_id: 10, description: "vital wheat gluten" },
        { id: 479, allergen_id: 10, description: "wheat" },
        { id: 480, allergen_id: 10, description: "wheat berries" },
        { id: 481, allergen_id: 10, description: "wheat bran" },
        { id: 482, allergen_id: 10, description: "wheat flour" },
        { id: 483, allergen_id: 10, description: "wheat germ" },
        { id: 484, allergen_id: 10, description: "wheat germ oil" },
        { id: 485, allergen_id: 10, description: "wheat gluten" },
        { id: 486, allergen_id: 10, description: "wheat protein isolate" },
        { id: 487, allergen_id: 10, description: "wheat sprouts" },
        { id: 488, allergen_id: 10, description: "wheat starch" },
        { id: 489, allergen_id: 10, description: "wheatgrass" },
        { id: 490, allergen_id: 10, description: "white flour" },
        { id: 491, allergen_id: 10, description: "whole wheat" },
        { id: 492, allergen_id: 10, description: "whole wheat bread" },
        { id: 493, allergen_id: 10, description: "whole wheat flour" }
      ]);
    })
    .then(() => {
      return knex.raw(
        `SELECT setval('${table}_id_seq', (SELECT MAX(id) FROM ${table}));`
      );
    });
};
